version: '3.8'
services:
  imdb-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imdb-api 
    restart: always
    ports:
      - 8080:3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgresprisma
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-prisma-docker-db